# Generated by Django 5.1.6 on 2025-03-06 21:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('name', config='russian'), name='name_gin'), django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('description', config='russian'), name='desc_gin')],
            },
        ),
    ]
