# Generated by Django 5.1.6 on 2025-03-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulltext_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(related_name='items', to='fulltext_demo.category'),
        ),
    ]
