# Generated by Django 5.1.6 on 2025-03-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulltext_demo', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flat_categories',
            field=models.ManyToManyField(related_name='deep_items', to='fulltext_demo.category'),
        ),
    ]
