# Generated by Django 5.1.6 on 2025-03-08 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulltext_demo', '0004_item_flat_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='flat_categories',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_kids', to='fulltext_demo.category'),
        ),
    ]
