# Generated by Django 5.1.6 on 2025-03-11 09:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulltext_demo', '0005_remove_item_flat_categories_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ancestors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
